#!/usr/bin/env bash
# install nginx & configure to listen on port 80. Print Hello world

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chown -R "$USER":"$USER" /var/www/html/
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
sudo systemctl reload nginx