#!/usr/bin/env bash
#permanent 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/http {/a \    server {\n        listen 80;\n        location /redirect_me {\n            return 301 https://www.youtube.com;\n        }\n    }' /etc/nginx/nginx.conf
sudo service nginx start

