#!/usr/bin/env bash
#404 page not found

#!/usr/bin/env bash
#permanent 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/server {/a \    error_page 404 /custom_404.html;\n    }' /etc/nginx/sites-available/default
cd /var/www/html/ || exit
sudo touch custom_404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo nginx -s reload