#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chown -R "$USER":"$USER" /var/www/html/
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/server {/a \    location /redirect_me {\n            return 301 https://www.youtube.com;\n        }\n    }' /etc/nginx/sites-available/default
sudo sed -i '/server {/a \    error_page 404 /custom_404.html;\n    }' /etc/nginx/sites-available/default
cd /var/www/html/ || exit
sudo touch custom_404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo nginx -s reload