#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend muhayminolalekan.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 301579-web-01 54.196.28.88:80
        server 301579-web-02 34.201.174.193:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart