#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sudo apt-get update
sudo apt-get install haproxy -y

# edit config file
echo "frontend front_servers
        bind *:80
        mode http
        default_backend servers

    backend servers
    balance roundrobin
    server 301579-web-01 54.237.25.65:80 check
    server 301579-web-02 52.87.230.182:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart