#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in ls ./*
do
    filename=$(basename "$file")
    name_after_cut=$(echo "$filename" | cut -d'-' -f2-)
    echo "$name_after_cut"
done