#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.
mysqldump -uroot -p"$1" --all-databases > backup.sql
sleep 3
if [ $? -eq 0 ]
then
    tar -czvf "$(date +%d-%m-%Y)".tar.gz backup.sql
fi